### ISSUE TITLE
V2.2.0 issue while installed using SPM

### ISSUE THREAD

**Issue by vishal-zest** [customerglu/CG-iOS-SDK#11]
Hello Customer Glu SDK team.

I am trying to install latest V2.2.0 version using SPM but it is throwing error while building.

I can see from commits you guys have added Sentry and Lottie as dependency for CocoaPod in "PodSpec" file but for SPM you guys need to update same in "Package.swift" file for  "dependencies".

Also find screenshots for same.

![Screenshot 2022-12-30 at 10 46 35 PM](https://user-images.githubusercontent.com/103772222/210096848-d1d4f647-0577-4d8c-93e9-dcf6d4ce9840.png)
![Screenshot 2022-12-30 at 10 47 09 PM](https://user-images.githubusercontent.com/103772222/210096852-8bf7f8b0-8e95-4cc9-95f5-1131fcf1a13d.png)
![Screenshot 2022-12-30 at 10 47 24 PM](https://user-images.githubusercontent.com/103772222/210096857-bfbc4a2d-f05a-46dc-afc6-ad6e841f837d.png)

**Comment by vishal-zest** [comment]
@androidguy30  please update on this.

**Comment by androidguy30** [comment]
@vishal-zest We have resolved this issue in v2.3.0  SDK, kindly update to the same version
