### ISSUE TITLE
Firebase crash on SDK instance initialization

### ISSUE THREAD

**Issue by varindersingh-dewsolutions-MarTech** [customerglu/CG-iOS-SDK#31]
let customerglu = CustomerGlu.getInstance

Firebase crash on this initialization 

Crash ref 
one-time initialization function for shared
crash_info_entry_0
BUG IN CLIENT OF LIBDISPATCH: trying to lock recursively

Using 
Xcode 14.2
SDK version - 2.3.3

**Comment by androidguy30** [comment]
@varindersingh-dewsolutions-MarTech Can you please share the complete Crash log to debug the issue

**Comment by varindersingh-dewsolutions-MarTech** [comment]
[com.tata.tatacliq_issue_88125ca70faafef7af97b1eff3665dc1_crash_session_c65f74e16f4c41fc938d5a5be2fee60c_DNE_0_v2_stacktrace.txt](https://github.com/customerglu/CG-iOS-SDK/files/11221277/com.tata.tatacliq_issue_88125ca70faafef7af97b1eff3665dc1_crash_session_c65f74e16f4c41fc938d5a5be2fee60c_DNE_0_v2_stacktrace.txt)

**Comment by varindersingh-dewsolutions-MarTech** [comment]
@androidguy30 , Any update on this ? this is impacting hugely our user base.
need to fix this ASAP.

**Comment by androidguy30** [comment]
@varindersingh-dewsolutions-MarTech we have checked on our end, we are unable to recreate the issue.
